### ISSUE TITLE
Will it work with MacOS VM?

### ISSUE THREAD

**Issue by vivekmiyani** [xushichangdesmond/screamer#1]
@xushichangdesmond I have MacOS VM and it does not have any audio output, It is running on Linux guest (Which have audio output).
So Can I use this to play the audio produced by MacOS's youtube video (or anything else)?

**Comment by xushichangdesmond** [comment]
It is using standard java audio API to playback audio, so technically yes for audio output, but the main audio input it was designed for, is for use with a windows driver https://github.com/duncanthrax/scream.

**Comment by vivekmiyani** [comment]
Okay I see.
